/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillesRouteImport } from './routes/villes'
import { Route as VenteSpasRouteImport } from './routes/vente-spas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as PiscineRouteImport } from './routes/piscine'
import { Route as PiecesRouteImport } from './routes/pieces'
import { Route as EnRouteImport } from './routes/en'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenteSpaVilleRouteImport } from './routes/vente-spa.$ville'
import { Route as ReparationSpaVilleRouteImport } from './routes/reparation-spa.$ville'
import { Route as PiecesSpaVilleRouteImport } from './routes/pieces-spa.$ville'
import { Route as OuvertureSpaVilleRouteImport } from './routes/ouverture-spa.$ville'
import { Route as OuverturePiscineVilleRouteImport } from './routes/ouverture-piscine.$ville'
import { Route as NettoyagePiscineVilleRouteImport } from './routes/nettoyage-piscine.$ville'
import { Route as InstallationSpaVilleRouteImport } from './routes/installation-spa.$ville'
import { Route as HotTubRepairVilleRouteImport } from './routes/hot-tub-repair.$ville'
import { Route as HotTubMaintenanceVilleRouteImport } from './routes/hot-tub-maintenance.$ville'
import { Route as FermetureSpaVilleRouteImport } from './routes/fermeture-spa.$ville'
import { Route as FermeturePiscineVilleRouteImport } from './routes/fermeture-piscine.$ville'
import { Route as EntretienSpaVilleRouteImport } from './routes/entretien-spa.$ville'
import { Route as EntretienPiscineVilleRouteImport } from './routes/entretien-piscine.$ville'

const VillesRoute = VillesRouteImport.update({
  id: '/villes',
  path: '/villes',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteSpasRoute = VenteSpasRouteImport.update({
  id: '/vente-spas',
  path: '/vente-spas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const PiscineRoute = PiscineRouteImport.update({
  id: '/piscine',
  path: '/piscine',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesRoute = PiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteSpaVilleRoute = VenteSpaVilleRouteImport.update({
  id: '/vente-spa/$ville',
  path: '/vente-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparationSpaVilleRoute = ReparationSpaVilleRouteImport.update({
  id: '/reparation-spa/$ville',
  path: '/reparation-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesSpaVilleRoute = PiecesSpaVilleRouteImport.update({
  id: '/pieces-spa/$ville',
  path: '/pieces-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvertureSpaVilleRoute = OuvertureSpaVilleRouteImport.update({
  id: '/ouverture-spa/$ville',
  path: '/ouverture-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const OuverturePiscineVilleRoute = OuverturePiscineVilleRouteImport.update({
  id: '/ouverture-piscine/$ville',
  path: '/ouverture-piscine/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyagePiscineVilleRoute = NettoyagePiscineVilleRouteImport.update({
  id: '/nettoyage-piscine/$ville',
  path: '/nettoyage-piscine/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationSpaVilleRoute = InstallationSpaVilleRouteImport.update({
  id: '/installation-spa/$ville',
  path: '/installation-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const HotTubRepairVilleRoute = HotTubRepairVilleRouteImport.update({
  id: '/hot-tub-repair/$ville',
  path: '/hot-tub-repair/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const HotTubMaintenanceVilleRoute = HotTubMaintenanceVilleRouteImport.update({
  id: '/hot-tub-maintenance/$ville',
  path: '/hot-tub-maintenance/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const FermetureSpaVilleRoute = FermetureSpaVilleRouteImport.update({
  id: '/fermeture-spa/$ville',
  path: '/fermeture-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const FermeturePiscineVilleRoute = FermeturePiscineVilleRouteImport.update({
  id: '/fermeture-piscine/$ville',
  path: '/fermeture-piscine/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienSpaVilleRoute = EntretienSpaVilleRouteImport.update({
  id: '/entretien-spa/$ville',
  path: '/entretien-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienPiscineVilleRoute = EntretienPiscineVilleRouteImport.update({
  id: '/entretien-piscine/$ville',
  path: '/entretien-piscine/$ville',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/pieces': typeof PiecesRoute
  '/piscine': typeof PiscineRoute
  '/regions': typeof RegionsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vente-spas': typeof VenteSpasRoute
  '/villes': typeof VillesRoute
  '/entretien-piscine/$ville': typeof EntretienPiscineVilleRoute
  '/entretien-spa/$ville': typeof EntretienSpaVilleRoute
  '/fermeture-piscine/$ville': typeof FermeturePiscineVilleRoute
  '/fermeture-spa/$ville': typeof FermetureSpaVilleRoute
  '/hot-tub-maintenance/$ville': typeof HotTubMaintenanceVilleRoute
  '/hot-tub-repair/$ville': typeof HotTubRepairVilleRoute
  '/installation-spa/$ville': typeof InstallationSpaVilleRoute
  '/nettoyage-piscine/$ville': typeof NettoyagePiscineVilleRoute
  '/ouverture-piscine/$ville': typeof OuverturePiscineVilleRoute
  '/ouverture-spa/$ville': typeof OuvertureSpaVilleRoute
  '/pieces-spa/$ville': typeof PiecesSpaVilleRoute
  '/reparation-spa/$ville': typeof ReparationSpaVilleRoute
  '/vente-spa/$ville': typeof VenteSpaVilleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/pieces': typeof PiecesRoute
  '/piscine': typeof PiscineRoute
  '/regions': typeof RegionsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vente-spas': typeof VenteSpasRoute
  '/villes': typeof VillesRoute
  '/entretien-piscine/$ville': typeof EntretienPiscineVilleRoute
  '/entretien-spa/$ville': typeof EntretienSpaVilleRoute
  '/fermeture-piscine/$ville': typeof FermeturePiscineVilleRoute
  '/fermeture-spa/$ville': typeof FermetureSpaVilleRoute
  '/hot-tub-maintenance/$ville': typeof HotTubMaintenanceVilleRoute
  '/hot-tub-repair/$ville': typeof HotTubRepairVilleRoute
  '/installation-spa/$ville': typeof InstallationSpaVilleRoute
  '/nettoyage-piscine/$ville': typeof NettoyagePiscineVilleRoute
  '/ouverture-piscine/$ville': typeof OuverturePiscineVilleRoute
  '/ouverture-spa/$ville': typeof OuvertureSpaVilleRoute
  '/pieces-spa/$ville': typeof PiecesSpaVilleRoute
  '/reparation-spa/$ville': typeof ReparationSpaVilleRoute
  '/vente-spa/$ville': typeof VenteSpaVilleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/pieces': typeof PiecesRoute
  '/piscine': typeof PiscineRoute
  '/regions': typeof RegionsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vente-spas': typeof VenteSpasRoute
  '/villes': typeof VillesRoute
  '/entretien-piscine/$ville': typeof EntretienPiscineVilleRoute
  '/entretien-spa/$ville': typeof EntretienSpaVilleRoute
  '/fermeture-piscine/$ville': typeof FermeturePiscineVilleRoute
  '/fermeture-spa/$ville': typeof FermetureSpaVilleRoute
  '/hot-tub-maintenance/$ville': typeof HotTubMaintenanceVilleRoute
  '/hot-tub-repair/$ville': typeof HotTubRepairVilleRoute
  '/installation-spa/$ville': typeof InstallationSpaVilleRoute
  '/nettoyage-piscine/$ville': typeof NettoyagePiscineVilleRoute
  '/ouverture-piscine/$ville': typeof OuverturePiscineVilleRoute
  '/ouverture-spa/$ville': typeof OuvertureSpaVilleRoute
  '/pieces-spa/$ville': typeof PiecesSpaVilleRoute
  '/reparation-spa/$ville': typeof ReparationSpaVilleRoute
  '/vente-spa/$ville': typeof VenteSpaVilleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/en'
    | '/pieces'
    | '/piscine'
    | '/regions'
    | '/services'
    | '/sitemap.xml'
    | '/vente-spas'
    | '/villes'
    | '/entretien-piscine/$ville'
    | '/entretien-spa/$ville'
    | '/fermeture-piscine/$ville'
    | '/fermeture-spa/$ville'
    | '/hot-tub-maintenance/$ville'
    | '/hot-tub-repair/$ville'
    | '/installation-spa/$ville'
    | '/nettoyage-piscine/$ville'
    | '/ouverture-piscine/$ville'
    | '/ouverture-spa/$ville'
    | '/pieces-spa/$ville'
    | '/reparation-spa/$ville'
    | '/vente-spa/$ville'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/en'
    | '/pieces'
    | '/piscine'
    | '/regions'
    | '/services'
    | '/sitemap.xml'
    | '/vente-spas'
    | '/villes'
    | '/entretien-piscine/$ville'
    | '/entretien-spa/$ville'
    | '/fermeture-piscine/$ville'
    | '/fermeture-spa/$ville'
    | '/hot-tub-maintenance/$ville'
    | '/hot-tub-repair/$ville'
    | '/installation-spa/$ville'
    | '/nettoyage-piscine/$ville'
    | '/ouverture-piscine/$ville'
    | '/ouverture-spa/$ville'
    | '/pieces-spa/$ville'
    | '/reparation-spa/$ville'
    | '/vente-spa/$ville'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/en'
    | '/pieces'
    | '/piscine'
    | '/regions'
    | '/services'
    | '/sitemap.xml'
    | '/vente-spas'
    | '/villes'
    | '/entretien-piscine/$ville'
    | '/entretien-spa/$ville'
    | '/fermeture-piscine/$ville'
    | '/fermeture-spa/$ville'
    | '/hot-tub-maintenance/$ville'
    | '/hot-tub-repair/$ville'
    | '/installation-spa/$ville'
    | '/nettoyage-piscine/$ville'
    | '/ouverture-piscine/$ville'
    | '/ouverture-spa/$ville'
    | '/pieces-spa/$ville'
    | '/reparation-spa/$ville'
    | '/vente-spa/$ville'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EnRoute: typeof EnRoute
  PiecesRoute: typeof PiecesRoute
  PiscineRoute: typeof PiscineRoute
  RegionsRoute: typeof RegionsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenteSpasRoute: typeof VenteSpasRoute
  VillesRoute: typeof VillesRoute
  EntretienPiscineVilleRoute: typeof EntretienPiscineVilleRoute
  EntretienSpaVilleRoute: typeof EntretienSpaVilleRoute
  FermeturePiscineVilleRoute: typeof FermeturePiscineVilleRoute
  FermetureSpaVilleRoute: typeof FermetureSpaVilleRoute
  HotTubMaintenanceVilleRoute: typeof HotTubMaintenanceVilleRoute
  HotTubRepairVilleRoute: typeof HotTubRepairVilleRoute
  InstallationSpaVilleRoute: typeof InstallationSpaVilleRoute
  NettoyagePiscineVilleRoute: typeof NettoyagePiscineVilleRoute
  OuverturePiscineVilleRoute: typeof OuverturePiscineVilleRoute
  OuvertureSpaVilleRoute: typeof OuvertureSpaVilleRoute
  PiecesSpaVilleRoute: typeof PiecesSpaVilleRoute
  ReparationSpaVilleRoute: typeof ReparationSpaVilleRoute
  VenteSpaVilleRoute: typeof VenteSpaVilleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villes': {
      id: '/villes'
      path: '/villes'
      fullPath: '/villes'
      preLoaderRoute: typeof VillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente-spas': {
      id: '/vente-spas'
      path: '/vente-spas'
      fullPath: '/vente-spas'
      preLoaderRoute: typeof VenteSpasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piscine': {
      id: '/piscine'
      path: '/piscine'
      fullPath: '/piscine'
      preLoaderRoute: typeof PiscineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces': {
      id: '/pieces'
      path: '/pieces'
      fullPath: '/pieces'
      preLoaderRoute: typeof PiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente-spa/$ville': {
      id: '/vente-spa/$ville'
      path: '/vente-spa/$ville'
      fullPath: '/vente-spa/$ville'
      preLoaderRoute: typeof VenteSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparation-spa/$ville': {
      id: '/reparation-spa/$ville'
      path: '/reparation-spa/$ville'
      fullPath: '/reparation-spa/$ville'
      preLoaderRoute: typeof ReparationSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces-spa/$ville': {
      id: '/pieces-spa/$ville'
      path: '/pieces-spa/$ville'
      fullPath: '/pieces-spa/$ville'
      preLoaderRoute: typeof PiecesSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouverture-spa/$ville': {
      id: '/ouverture-spa/$ville'
      path: '/ouverture-spa/$ville'
      fullPath: '/ouverture-spa/$ville'
      preLoaderRoute: typeof OuvertureSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouverture-piscine/$ville': {
      id: '/ouverture-piscine/$ville'
      path: '/ouverture-piscine/$ville'
      fullPath: '/ouverture-piscine/$ville'
      preLoaderRoute: typeof OuverturePiscineVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-piscine/$ville': {
      id: '/nettoyage-piscine/$ville'
      path: '/nettoyage-piscine/$ville'
      fullPath: '/nettoyage-piscine/$ville'
      preLoaderRoute: typeof NettoyagePiscineVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation-spa/$ville': {
      id: '/installation-spa/$ville'
      path: '/installation-spa/$ville'
      fullPath: '/installation-spa/$ville'
      preLoaderRoute: typeof InstallationSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-tub-repair/$ville': {
      id: '/hot-tub-repair/$ville'
      path: '/hot-tub-repair/$ville'
      fullPath: '/hot-tub-repair/$ville'
      preLoaderRoute: typeof HotTubRepairVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-tub-maintenance/$ville': {
      id: '/hot-tub-maintenance/$ville'
      path: '/hot-tub-maintenance/$ville'
      fullPath: '/hot-tub-maintenance/$ville'
      preLoaderRoute: typeof HotTubMaintenanceVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fermeture-spa/$ville': {
      id: '/fermeture-spa/$ville'
      path: '/fermeture-spa/$ville'
      fullPath: '/fermeture-spa/$ville'
      preLoaderRoute: typeof FermetureSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fermeture-piscine/$ville': {
      id: '/fermeture-piscine/$ville'
      path: '/fermeture-piscine/$ville'
      fullPath: '/fermeture-piscine/$ville'
      preLoaderRoute: typeof FermeturePiscineVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien-spa/$ville': {
      id: '/entretien-spa/$ville'
      path: '/entretien-spa/$ville'
      fullPath: '/entretien-spa/$ville'
      preLoaderRoute: typeof EntretienSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien-piscine/$ville': {
      id: '/entretien-piscine/$ville'
      path: '/entretien-piscine/$ville'
      fullPath: '/entretien-piscine/$ville'
      preLoaderRoute: typeof EntretienPiscineVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EnRoute: EnRoute,
  PiecesRoute: PiecesRoute,
  PiscineRoute: PiscineRoute,
  RegionsRoute: RegionsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenteSpasRoute: VenteSpasRoute,
  VillesRoute: VillesRoute,
  EntretienPiscineVilleRoute: EntretienPiscineVilleRoute,
  EntretienSpaVilleRoute: EntretienSpaVilleRoute,
  FermeturePiscineVilleRoute: FermeturePiscineVilleRoute,
  FermetureSpaVilleRoute: FermetureSpaVilleRoute,
  HotTubMaintenanceVilleRoute: HotTubMaintenanceVilleRoute,
  HotTubRepairVilleRoute: HotTubRepairVilleRoute,
  InstallationSpaVilleRoute: InstallationSpaVilleRoute,
  NettoyagePiscineVilleRoute: NettoyagePiscineVilleRoute,
  OuverturePiscineVilleRoute: OuverturePiscineVilleRoute,
  OuvertureSpaVilleRoute: OuvertureSpaVilleRoute,
  PiecesSpaVilleRoute: PiecesSpaVilleRoute,
  ReparationSpaVilleRoute: ReparationSpaVilleRoute,
  VenteSpaVilleRoute: VenteSpaVilleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
