/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillesRouteImport } from './routes/villes'
import { Route as VenteSpasRouteImport } from './routes/vente-spas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as PiscineRouteImport } from './routes/piscine'
import { Route as PiecesRouteImport } from './routes/pieces'
import { Route as EnRouteImport } from './routes/en'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReparationSpaVilleRouteImport } from './routes/reparation-spa.$ville'
import { Route as OuvertureSpaVilleRouteImport } from './routes/ouverture-spa.$ville'
import { Route as InstallationSpaVilleRouteImport } from './routes/installation-spa.$ville'
import { Route as FermetureSpaVilleRouteImport } from './routes/fermeture-spa.$ville'
import { Route as EntretienSpaVilleRouteImport } from './routes/entretien-spa.$ville'

const VillesRoute = VillesRouteImport.update({
  id: '/villes',
  path: '/villes',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteSpasRoute = VenteSpasRouteImport.update({
  id: '/vente-spas',
  path: '/vente-spas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const PiscineRoute = PiscineRouteImport.update({
  id: '/piscine',
  path: '/piscine',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesRoute = PiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparationSpaVilleRoute = ReparationSpaVilleRouteImport.update({
  id: '/reparation-spa/$ville',
  path: '/reparation-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvertureSpaVilleRoute = OuvertureSpaVilleRouteImport.update({
  id: '/ouverture-spa/$ville',
  path: '/ouverture-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationSpaVilleRoute = InstallationSpaVilleRouteImport.update({
  id: '/installation-spa/$ville',
  path: '/installation-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const FermetureSpaVilleRoute = FermetureSpaVilleRouteImport.update({
  id: '/fermeture-spa/$ville',
  path: '/fermeture-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretienSpaVilleRoute = EntretienSpaVilleRouteImport.update({
  id: '/entretien-spa/$ville',
  path: '/entretien-spa/$ville',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/pieces': typeof PiecesRoute
  '/piscine': typeof PiscineRoute
  '/regions': typeof RegionsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vente-spas': typeof VenteSpasRoute
  '/villes': typeof VillesRoute
  '/entretien-spa/$ville': typeof EntretienSpaVilleRoute
  '/fermeture-spa/$ville': typeof FermetureSpaVilleRoute
  '/installation-spa/$ville': typeof InstallationSpaVilleRoute
  '/ouverture-spa/$ville': typeof OuvertureSpaVilleRoute
  '/reparation-spa/$ville': typeof ReparationSpaVilleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/pieces': typeof PiecesRoute
  '/piscine': typeof PiscineRoute
  '/regions': typeof RegionsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vente-spas': typeof VenteSpasRoute
  '/villes': typeof VillesRoute
  '/entretien-spa/$ville': typeof EntretienSpaVilleRoute
  '/fermeture-spa/$ville': typeof FermetureSpaVilleRoute
  '/installation-spa/$ville': typeof InstallationSpaVilleRoute
  '/ouverture-spa/$ville': typeof OuvertureSpaVilleRoute
  '/reparation-spa/$ville': typeof ReparationSpaVilleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/pieces': typeof PiecesRoute
  '/piscine': typeof PiscineRoute
  '/regions': typeof RegionsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vente-spas': typeof VenteSpasRoute
  '/villes': typeof VillesRoute
  '/entretien-spa/$ville': typeof EntretienSpaVilleRoute
  '/fermeture-spa/$ville': typeof FermetureSpaVilleRoute
  '/installation-spa/$ville': typeof InstallationSpaVilleRoute
  '/ouverture-spa/$ville': typeof OuvertureSpaVilleRoute
  '/reparation-spa/$ville': typeof ReparationSpaVilleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/en'
    | '/pieces'
    | '/piscine'
    | '/regions'
    | '/services'
    | '/sitemap.xml'
    | '/vente-spas'
    | '/villes'
    | '/entretien-spa/$ville'
    | '/fermeture-spa/$ville'
    | '/installation-spa/$ville'
    | '/ouverture-spa/$ville'
    | '/reparation-spa/$ville'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/en'
    | '/pieces'
    | '/piscine'
    | '/regions'
    | '/services'
    | '/sitemap.xml'
    | '/vente-spas'
    | '/villes'
    | '/entretien-spa/$ville'
    | '/fermeture-spa/$ville'
    | '/installation-spa/$ville'
    | '/ouverture-spa/$ville'
    | '/reparation-spa/$ville'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/en'
    | '/pieces'
    | '/piscine'
    | '/regions'
    | '/services'
    | '/sitemap.xml'
    | '/vente-spas'
    | '/villes'
    | '/entretien-spa/$ville'
    | '/fermeture-spa/$ville'
    | '/installation-spa/$ville'
    | '/ouverture-spa/$ville'
    | '/reparation-spa/$ville'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EnRoute: typeof EnRoute
  PiecesRoute: typeof PiecesRoute
  PiscineRoute: typeof PiscineRoute
  RegionsRoute: typeof RegionsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenteSpasRoute: typeof VenteSpasRoute
  VillesRoute: typeof VillesRoute
  EntretienSpaVilleRoute: typeof EntretienSpaVilleRoute
  FermetureSpaVilleRoute: typeof FermetureSpaVilleRoute
  InstallationSpaVilleRoute: typeof InstallationSpaVilleRoute
  OuvertureSpaVilleRoute: typeof OuvertureSpaVilleRoute
  ReparationSpaVilleRoute: typeof ReparationSpaVilleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villes': {
      id: '/villes'
      path: '/villes'
      fullPath: '/villes'
      preLoaderRoute: typeof VillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente-spas': {
      id: '/vente-spas'
      path: '/vente-spas'
      fullPath: '/vente-spas'
      preLoaderRoute: typeof VenteSpasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piscine': {
      id: '/piscine'
      path: '/piscine'
      fullPath: '/piscine'
      preLoaderRoute: typeof PiscineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces': {
      id: '/pieces'
      path: '/pieces'
      fullPath: '/pieces'
      preLoaderRoute: typeof PiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparation-spa/$ville': {
      id: '/reparation-spa/$ville'
      path: '/reparation-spa/$ville'
      fullPath: '/reparation-spa/$ville'
      preLoaderRoute: typeof ReparationSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouverture-spa/$ville': {
      id: '/ouverture-spa/$ville'
      path: '/ouverture-spa/$ville'
      fullPath: '/ouverture-spa/$ville'
      preLoaderRoute: typeof OuvertureSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation-spa/$ville': {
      id: '/installation-spa/$ville'
      path: '/installation-spa/$ville'
      fullPath: '/installation-spa/$ville'
      preLoaderRoute: typeof InstallationSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fermeture-spa/$ville': {
      id: '/fermeture-spa/$ville'
      path: '/fermeture-spa/$ville'
      fullPath: '/fermeture-spa/$ville'
      preLoaderRoute: typeof FermetureSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretien-spa/$ville': {
      id: '/entretien-spa/$ville'
      path: '/entretien-spa/$ville'
      fullPath: '/entretien-spa/$ville'
      preLoaderRoute: typeof EntretienSpaVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EnRoute: EnRoute,
  PiecesRoute: PiecesRoute,
  PiscineRoute: PiscineRoute,
  RegionsRoute: RegionsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenteSpasRoute: VenteSpasRoute,
  VillesRoute: VillesRoute,
  EntretienSpaVilleRoute: EntretienSpaVilleRoute,
  FermetureSpaVilleRoute: FermetureSpaVilleRoute,
  InstallationSpaVilleRoute: InstallationSpaVilleRoute,
  OuvertureSpaVilleRoute: OuvertureSpaVilleRoute,
  ReparationSpaVilleRoute: ReparationSpaVilleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
